---
- hosts: '{{ hosts }}'
  remote_user: root
  tasks:
  - name: Add Hosts internal IP
    blockinfile:
     block: "{{ lookup('file', './template/add_hosts') }}"
     dest: "/etc/hosts"
     backup: yes
     when internal_ip_allow == "YES"
  - name: Add Hosts Public IP
    blockinfile:
     block: "{{ lookup('file', './template/add_hosts_pub-ip') }}"
     dest: "/etc/hosts"
     backup: yes
     when internal_ip_allow == "NO"
