---
- hosts: '{{ hosts }}'
  vars:
     spacewalk_server: '{{ spacewalk_server }}'
  remote_user: root
  tasks:
   - name: Cleanup Package for CentOS
     shell: rpm -e rhn-org-trusted-ssl-cert
     when: ansible_distribution == "CentOS"
     
   - name: Cleanup Package for CentOS
     shell: rpm -Uvh http://lsm.lax10.vpls.net/pub/rhn-org-trusted-ssl-cert-1.0-3.noarch.rpm
     when: ansible_distribution == "CentOS"
     
   - name: Install KEY 
     get_url: url=https://"{{ spacewalk_server }}"/pub/RHN-ORG-TRUSTED-SSL-CERT dest=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT validate_certs=no
     when: ansible_distribution == "Ubuntu"
   
   - name: Register system to Spacewalk (CentOS 7 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-centos7-x86_64 --force
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='7' and ansible_userspace_architecture == 'x86_64'

   - name: Register system to Spacewalk (CentOS 6 i386)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-centos6-i386 --force
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6' and ansible_userspace_architecture == 'i386'

   - name: Register system to Spacewalk (CentOS 6 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-centos6-x86_64 --force
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='6' and ansible_userspace_architecture == 'x86_64'
   - name: Register system to Spacewalk (CentOS 5 i386)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-centos5-i386 --force
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='5' and ansible_userspace_architecture == 'i386'

   - name: Register system to Spacewalk (CentOS 5 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-centos5-x86_64 --force
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='5' and ansible_userspace_architecture == 'x86_64'

   - name: Register system to Spacewalk (Fedora 24 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-fedora24-x86_64 --force
     when: ansible_distribution == "Fedora" and ansible_distribution_major_version =='24' and ansible_userspace_architecture == 'x86_64'

   - name: Register system to Spacewalk (Ubuntu 14 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-ubuntu-14.04-trusty-amd64 --force
     when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='14' and ansible_userspace_architecture == 'x86_64'
     ignore_errors: yes

   - name: Register system to Spacewalk (Ubuntu 16 x86_64)
     shell: rhnreg_ks --serverUrl=https://"{{ spacewalk_server }}"/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=1-ubuntu-16.04-xenial-amd64 --force
     when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='16' and ansible_userspace_architecture == 'x86_64'
     
   - name: Confing osad SSL CA CentOS
     lineinfile: dest="{{ item.dest }}" regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present
     with_items:
       - { dest: '/etc/yum/pluginconf.d/rhnplugin.conf' ,regexp: '^gpgcheck', insertbefore: '^gpgcheck' , line: 'gpgcheck = 0'}
     when: ansible_distribution == "CentOS" 

   - name: Confing osad SSL CA Fedora
     lineinfile: dest="{{ item.dest }}" regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present
     with_items:
       - { dest: '/etc/dnf/plugins/spacewalk.conf' ,regexp: '^gpgcheck', insertbefore: '^gpgcheck' , line: 'gpgcheck = 0'}
     when: ansible_distribution == "Fedora"

   - name: Confing osad SSL CA
     lineinfile: dest="{{ item.dest }}" regexp="{{ item.regexp }}" insertbefore="{{ item.insertbefore }}" line="{{ item.line }}" state=present
     with_items:
       - { dest: '/etc/sysconfig/rhn/osad.conf' ,regexp: '^osa_ssl_cert', insertbefore: '^osa_ssl_cert' , line: 'osa_ssl_cert = /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT'}

   - name: Start and enable osad [CentOS 7 and Fedora and Ubuntu 16]
     systemd: state=restarted name=osad enabled=yes
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version =='7' or  ansible_distribution == "Fedora" and ansible_distribution_major_version =='24' or ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='16'

   - name: Start and enable osad [CentOS 6 and Ubuntu 14]
     service: state=restarted name=osad enabled=yes
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '6' or ansible_distribution == "Ubuntu" and ansible_distribution_major_version =='14' 

   - name: Enable rhn-actions-control
     shell: rhn-actions-control --enable-all
     when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
